import type { Project } from './interfaces';

/**
 * Project list generated from markdown files
 * Sorted by date in descending order (newest first)
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate:projects' to regenerate this file
 * 
 * Generated on: 2025-10-11T23:08:08.068Z
 */

export const projects: Project[] = [
{
      id: 'sound-omnibar',
      slug: 'sound-omnibar',
      title: 'Sound Omnibar',
      description: 'Frameless window overlay for streaming Audio Speech Recognition using SimulStreaming',
      shortDescription: 'Streaming ASR window overlay',
      image: '/content/projects/images/sound-omnibar/banner.png',
      techStack: ['python', 'PyQt', 'whisper-streaming'],
      tags: ['ASR', 'Python', 'AI'],
      featured: true,
      date: '2025-10-06',
      githubRepo: 'https://github.com/Stymphalian/SoundOmnibar',
      showDetails: true,
      images: [
      {
        type: 'image',
        src: '/content/projects/images/sound-omnibar/preview.png',
        alt: 'Sound Omnibar Preview',
        caption: 'Streaming ASR window overlay'
      }
    ],
      videos: []
  },
{
      id: 'vscode-code-share-link',
      slug: 'vscode-code-share-link',
      title: 'VSCode Code Share Link',
      description: 'A VS Code extension that allows you to quickly generate and share code links to specific lines of code in your repository. Perfect for code reviews, documentation, and collaboration with keyboard shortcuts and context menu integration.',
      shortDescription: 'VS Code extension for generating shareable code links',
      image: '/content/projects/images/vscode-code-share-link/banner.png',
      techStack: ['TypeScript', 'VS Code API', 'Git', 'Node.js'],
      tags: ['TypeScript', 'VS Code Extension', 'Developer Tools', 'Git'],
      featured: true,
      date: '2025-09-20',
      githubRepo: 'https://github.com/Stymphalian/vscode-code-share-link',
      showDetails: true,
      images: [
      {
        type: 'image',
        src: '/content/projects/images/vscode-code-share-link/banner.png',
        alt: 'VSCode Code Share Link Extension',
        caption: 'VS Code extension for generating shareable code links'
      }
    ],
      videos: []
  },
{
      id: 'graph-editor',
      slug: 'graph_editor',
      title: 'Graph Editor',
      description: 'A web-based graph (node/edge) editor application designed to allow you to visually create and edit graphs. Features a text-panel for edge-list representation with bidirectional synchronization between text and visual editors. Built as an experiment with agentic coding using Cursor AI.',
      shortDescription: 'Interactive web-based graph editor with visual and text editing modes',
      image: '/content/projects/images/graph-editor/banner.png',
      techStack: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'D3.js', 'Jest'],
      tags: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'D3.js', 'Jest'],
      featured: true,
      date: '2025-09-01',
      githubRepo: 'https://github.com/Stymphalian/graph_editor',
      showDetails: true,
      images: [
      {
        type: 'image',
        src: '/content/projects/images/graph-editor/banner.png',
        alt: 'Graph Editor Interface',
        caption: 'Interactive graph editor with visual and text editing modes'
      },
      {
        type: 'image',
        src: '/content/projects/images/graph-editor/preview.png',
        alt: 'Graph Editor Preview',
        caption: 'Example of a graph being edited'
      }
    ],
      videos: []
  },
{
      id: 'ak-chibi-bot',
      slug: 'ak-chibi-bot',
      title: 'Arknights Chibi Twitch Bot',
      description: 'A twitch bot and browser source overlay to show Arknight chibis walking on your stream. Viewers can issue !chibi chat commands to choose their own operator, change skins and play different animations.',
      shortDescription: 'Twitch Bot and Browser Overlay for Arknights Chibis',
      image: '/content/projects/images/ak-chibi-bot/banner.png',
      techStack: ['React', 'Spine', 'Twitch API', 'Golang'],
      tags: ['React', 'Spine', 'Twitch API', 'Golang'],
      featured: true,
      date: '2024-06-10',
      liveDemo: 'https://akchibibot.stymphalian.top',
      githubRepo: 'https://github.com/stymphalian/ak_chibi_bot',
      showDetails: true,
      images: [
      {
        type: 'image',
        src: '/content/projects/images/ak-chibi-bot/banner.png',
        alt: 'Arknights Chibi Bot',
        caption: 'Arknights Chibi Twitch Bot and Overlay'
      }
    ],
      videos: []
  }
];
